name: neuraltfr
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pytorch
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - matplotlib
  - seaborn
  - joblib
  - tqdm
  - optuna